baseURL = "https://22delta.com/"
languageCode = "en-us"
title = "22 Delta Labs"

[params]
  description = "22 Delta Labs is a product development and software company that helps thinkers create value through engineering."
