baseURL = "https://www.22delta.com/"
languageCode = "en-us"
title = "Hire topnotch engineers & product designers to solve your core business problems | 22 Delta Labs"

[params]
  description = "22 Delta Labs is a product development and software company that helps thinkers create value through engineering."
