[[redirects]]
  from = "https://flamboyant-cray-8616e2.netlify.com/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[redirects]]
  from = "https://22d.io/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[redirects]]
  from = "https://www.22d.io/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    X-Server-Name = "www.22delta.com"
    Content-Security-Policy-Report-Only = "default-src 'self' 'unsafe-inline' https://d33wubrfki0l68.cloudfront.net; script-src 'self' https://d33wubrfki0l68.cloudfront.net https://www.googletagmanager.com/gtag/js https://www.google-analytics.com/analytics.js https://static.hotjar.com https://connect.facebook.net https://script.hotjar.com; style-src 'unsafe-inline' https://d33wubrfki0l68.cloudfront.net https://use.fontawesome.com/releases/v5.6.3/css/all.css; font-src 'self' data: https://d33wubrfki0l68.cloudfront.net; connect-src 'self' wss://ws2.hotjar.com/api/v1/client/ws https://in.hotjar.com/api; frame-src 'self' https://vars.hotjar.com https://staticxx.facebook.com https://www.facebook.com; form-action https://formcarry.com/s/RMFTDTWPPo4"
