[[redirects]]
  from = "https://flamboyant-cray-8616e2.netlify.com/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[redirects]]
  from = "https://22d.io/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[redirects]]
  from = "https://www.22d.io/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    X-Server-Name = "www.22delta.com"
    Content-Security-Policy-Report-Only = "default-src 'self' 'unsafe-inline' d33wubrfki0l68.cloudfront.net; script-src 'self' d33wubrfki0l68.cloudfront.net www.googletagmanager.com www.google-analytics.com static.hotjar.com connect.facebook.net script.hotjar.com; style-src 'unsafe-inline' d33wubrfki0l68.cloudfront.net use.fontawesome.com; font-src 'self' data: d33wubrfki0l68.cloudfront.net; connect-src 'self' *.hotjar.com; frame-src 'self' vars.hotjar.com staticxx.facebook.com www.facebook.com; form-action formcarry.com"
