[[redirects]]
  from = "https://flamboyant-cray-8616e2.netlify.com/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
