[[redirects]]
  from = "https://flamboyant-cray-8616e2.netlify.com/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[redirects]]
  from = "https://22d.io/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[redirects]]
  from = "https://www.22d.io/*"
  to = "https://www.22delta.com/:splat"

  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    X-Server-Name = "www.22delta.com"
    Content-Security-Policy-Report-Only = "default-src 'self' https://d33wubrfki0l68.cloudfront.net; style-src 'unsafe-inline' https://d33wubrfki0l68.cloudfront.net https://use.fontawesome.com/releases/v5.6.3/css/all.css; form-action https://formcarry.com/s/RMFTDTWPPo4"
